### ISSUE TITLE
TypeScript error (with 'pixi.js')?

### ISSUE THREAD

**Issue by Liquidream** [miltoncandelero/pixi-hotwire#3]
I'm new to PixiJS (+TypeScript!), but I'm getting the following error when starting your pixijselementals tutoral, and I wonder if you/someone can assist?

I created a new repo from your [pixi-hotwire](https://github.com/miltoncandelero/pixi-hotwire) template (very neat templating feature, didn't realise Github had this!).

I opened the repo in vscode, ran `npm install` and noticed I had the error...

![image](https://user-images.githubusercontent.com/2211678/162904752-d9b227f6-d63d-48a1-8908-821a197ef881.png)

```
Could not find a declaration file for module 'pixi.js'. 'C:/git-repos/pixijs-test/node_modules/pixi.js/dist/cjs/pixi.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/pixi.js` if it exists or add a new declaration (.d.ts) file containing `declare module 'pixi.js';`
```

I also ran `npm run start` and the sample code loads and runs fine. 👍

So it seems I'm just missing something, which is making TS unhappy (and stopping me from having intelliSense, I presume?) 🤔

Thanks in advance!

**Comment by miltoncandelero** [comment]
It looks like vscode didn't realize you ran the install.
It should fix itself once you restart vscode

**Comment by Liquidream** [comment]
You are absolutely correct - thank you! 🥳
(Can't believe I didn't try the ol' "turn off & on again" first... 🤦‍♂️)
