### ISSUE TITLE
Advice for TypeScript debugging with vscode?

### ISSUE THREAD

**Issue by Liquidream** [miltoncandelero/pixi-hotwire#4]
Hiya,
**Q) Do you have any suggestions how to get Breakpoints to work (from the source Typescript .ts files) within this project/node/webpack structure?**

Everything works great using the `npm run start` or build, as suggested. However, I'd really like to get debugging working, as that will be invaluable for anything larger.

I've tried to do it myself (found [this link](https://dirask.com/posts/VS-Code-debug-with-npm-run-jELw0p), but alas didn't work).
The closest I have is that I now have a launch.json file...
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "command": "npm run start",
            "name": "Debug PixiJS",
            "request": "launch",
            "type": "node-terminal"
        }
    ]
}
```
...which starts the webpack/node server and *seems* to have debugger attached:
```
PS C:\git-repos\kings-ransom> npm run start
Debugger attached.

> start
> webpack serve --mode=development

Debugger attached.
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:1234/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.1.88:1234/
15 assets
91 modules
webpack 5.72.0 compiled successfully in 4486 ms
```

However, the breakpoints don't get hit (they show as "Unbound breakpoint") and I *think* it might be because it's bound to the generated JS, and not linked back to the TS?  Dunno.

Either way, would be grateful if you (or anyone) could provide some pointers on how this can be setup.
Thanks in advance!

(P.S. - In case it helps, I'm on Windows with Edge browser, but my understanding is that this should work cross-platform, if done CORRECTLY! 😅)

**Comment by miltoncandelero** [comment]
These are the configs for different browsers, however you will need the corresponding vscode extensions
Put these inside your configuration object in the launch.json file
```json
		{
			"type": "chrome",
			"request": "launch",
			"name": "Launch Chrome against localhost",
			"url": "http://localhost:1234",
			"webRoot": "${workspaceFolder}"
		}
```
```json
		{
			"type": "firefox",
			"name": "Launch Firefox against localhost",
			"request": "launch",
			"reAttach": true,
			"url": "http://localhost:1234",
			"webRoot": "${workspaceFolder}",
		}
```
```json
		{
			"type": "edge",
			"name": "Launch Edge against localhost",
			"request": "launch",
			"url": "http://localhost:1234",
			"webRoot": "${workspaceFolder}"
		}
```

**Comment by Liquidream** [comment]
Ah, that's why it wasn't working - I *had* to launch the browser directly AND have npm already "run"-ning. 🤦‍♂️

Am very happy to report that my breakpoints are now being hit in vscode. 🥳
(albeit, had to change Edge port to also be 1234)

Thank you (...again!) 🙏
